<?php
/**
 * Plugin Name:       AHM AI Post Summary
 * Plugin URI:        https://wordpress.org/plugins/ahm-ai-post-summary/
 * Description:       Automatically generates AI-powered summaries for your blog posts using Google Gemini or OpenAI ChatGPT. Display summaries at the top of posts to improve reader engagement and SEO.
 * Version: 1.3.0
 * Requires at least: 5.6
 * Requires PHP:      7.4
 * Author:            Aung Hein Mynn
 * Author URI:        https://profiles.wordpress.org/aheinmynn/
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       ahm-ai-post-summary
 * Domain Path:       /languages
 *
 * AHM AI Post Summary is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * any later version.
 *
 * AHM AI Post Summary is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AHM AI Post Summary. If not, see https://www.gnu.org/licenses/gpl-2.0.html.
 *
 * @package AIPostSummary
 * @version 1.3.0
 * @author  Aung Hein Mynn
 * @license GPL-2.0-or-later
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Define plugin constants
define('AHMAIPSU_VERSION', '1.3.0');
define('AHMAIPSU_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('AHMAIPSU_PLUGIN_URL', plugin_dir_url(__FILE__));
define('AHMAIPSU_PLUGIN_FILE', __FILE__);

// Include required files
require_once AHMAIPSU_PLUGIN_DIR . 'includes/admin-settings.php';
require_once AHMAIPSU_PLUGIN_DIR . 'includes/post-editor.php';
require_once AHMAIPSU_PLUGIN_DIR . 'includes/api-handler.php';
require_once AHMAIPSU_PLUGIN_DIR . 'includes/generate-fingerprint.php';
require_once AHMAIPSU_PLUGIN_DIR . 'includes/destination-sync.php';
require_once AHMAIPSU_PLUGIN_DIR . 'includes/frontend-display.php';
require_once AHMAIPSU_PLUGIN_DIR . 'includes/block-summary.php';

// Activation hook
register_activation_hook(__FILE__, 'ahmaipsu_activate');

function ahmaipsu_activate() {
    // Set default options on activation
    $default_options = array(
        'ahmaipsu_global_enable' => false,
        'ahmaipsu_api_provider' => 'gemini',
        'ahmaipsu_api_key' => '',
        'ahmaipsu_model' => 'gemini-3.6-flash',
        'ahmaipsu_char_count' => 200,
        'ahmaipsu_post_types' => ['post'], // Default to posts only
        'ahmaipsu_disclaimer' => 'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.',
        'ahmaipsu_default_language' => 'auto',
        'ahmaipsu_theme' => 'classic',
        'ahmaipsu_content_type' => 'summary',
        'ahmaipsu_custom_summary_title' => '',
        'ahmaipsu_custom_key_takeaways_title' => '',
        'ahmaipsu_sync_excerpt' => 1,
        'ahmaipsu_sync_yoast' => 1,
        'ahmaipsu_sync_rankmath' => 1,
        'ahmaipsu_sync_on_regenerate' => 1,
        'ahmaipsu_sync_overwrite' => 0
    );
    
    add_option('ahmaipsu_settings', $default_options);
}

// Deactivation hook
register_deactivation_hook(__FILE__, 'ahmaipsu_deactivate');

function ahmaipsu_deactivate() {
    // Clean up temporary data if needed
    // Note: We don't delete user settings on deactivation
}

// Uninstall hook
register_uninstall_hook(__FILE__, 'ahmaipsu_uninstall');

function ahmaipsu_uninstall() {
    // Clean up all plugin data on uninstall
    delete_option('ahmaipsu_settings');
    
    // Remove all post meta
    delete_post_meta_by_key('_ahmaipsu_enabled');
    delete_post_meta_by_key('_ahmaipsu_content');
    delete_post_meta_by_key('_ahmaipsu_regenerate_flag');
    delete_post_meta_by_key('_ahmaipsu_content_type');
    delete_post_meta_by_key('_ahmaipsu_wrote_excerpt');
    delete_post_meta_by_key('_ahmaipsu_wrote_yoast');
    delete_post_meta_by_key('_ahmaipsu_wrote_rankmath');
    delete_post_meta_by_key('_ahmaipsu_generate_fingerprint');
    // Keep post_excerpt, Yoast, and Rank Math values.
}
