<?php
/**
 * Frontend display for AHM AI Post Summary plugin
 *
 * @package AIPostSummary
 * @since   1.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

add_filter('the_content', 'ahmaipsu_display_summary');

function ahmaipsu_display_summary($content) {
    // Only show on single posts/pages and main query
    if (!is_singular() || !is_main_query() || is_admin()) {
        return $content;
    }
    
    global $post;
    
    // Verify we have a valid post object
    if (!$post || !isset($post->ID)) {
        return $content;
    }
    
    $options = get_option('ahmaipsu_settings', array());
    $global_enabled = isset($options['ahmaipsu_global_enable']) ? $options['ahmaipsu_global_enable'] : false;
    $supported_post_types = isset($options['ahmaipsu_post_types']) ? $options['ahmaipsu_post_types'] : ['post'];
    
    // Check if current post type is supported
    if (!in_array($post->post_type, $supported_post_types)) {
        return $content;
    }
    $post_enabled = get_post_meta($post->ID, '_ahmaipsu_enabled', true);
    $summary = get_post_meta($post->ID, '_ahmaipsu_content', true);
    $content_type = get_post_meta($post->ID, '_ahmaipsu_content_type', true) ?: 'summary';
    
    if (!$global_enabled || !$post_enabled || empty($summary)) {
        return $content;
    }

    // Manual block or shortcode placement: do not also prepend.
    if (has_block('ahm-ai-post-summary/summary', $content) || has_shortcode($content, 'ahm_ai_post_summary') || has_shortcode($content, 'ahmaipsu')) {
        return $content;
    }
    
    // Get disclaimer text and theme from settings
    $disclaimer = isset($options['ahmaipsu_disclaimer']) ? 
        $options['ahmaipsu_disclaimer'] : 
        'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.';
    
    $theme = isset($options['ahmaipsu_theme']) ? $options['ahmaipsu_theme'] : 'classic';
    
    $summary_html = ahmaipsu_render_summary($summary, $disclaimer, $theme, $content_type);
    
    return $summary_html . $content;
}

function ahmaipsu_render_summary($summary, $disclaimer, $theme = 'classic', $content_type = 'summary', $show_title = true, $show_disclaimer = true) {
    $options = get_option('ahmaipsu_settings', array());
    
    $theme_classes = array(
        'classic' => 'ahmaipsu-theme-classic',
        'minimal' => 'ahmaipsu-theme-minimal',
        'modern' => 'ahmaipsu-theme-modern',
        'elegant' => 'ahmaipsu-theme-elegant',
        'card' => 'ahmaipsu-theme-card'
    );
    
    $theme_titles = array(
        'classic' => '📝 Summary',
        'minimal' => 'Summary',
        'modern' => '🤖 Summary',
        'elegant' => 'Summary',
        'card' => '📄 Summary'
    );
    
    // Adjust title for key takeaways
    if ($content_type === 'key_takeaways') {
        $theme_titles = array(
            'classic' => '🔑 Key Takeaways',
            'minimal' => 'Key Takeaways',
            'modern' => '🎯 Key Takeaways',
            'elegant' => 'Key Takeaways',
            'card' => '📋 Key Takeaways'
        );
    }
    
    // Use custom titles if set
    if ($content_type === 'summary' && !empty($options['ahmaipsu_custom_summary_title'])) {
        $theme_title = $options['ahmaipsu_custom_summary_title'];
    } elseif ($content_type === 'key_takeaways' && !empty($options['ahmaipsu_custom_key_takeaways_title'])) {
        $theme_title = $options['ahmaipsu_custom_key_takeaways_title'];
    } else {
        $theme_title = isset($theme_titles[$theme]) ? $theme_titles[$theme] : $theme_titles['classic'];
    }
    
    $theme_class = isset($theme_classes[$theme]) ? $theme_classes[$theme] : $theme_classes['classic'];
    
    // Format content based on type
    if ($content_type === 'key_takeaways') {
        // Convert to bulleted list if not already formatted
        $formatted_content = wp_kses_post($summary);
        if (strpos($formatted_content, '<ul>') === false && strpos($formatted_content, '<li>') === false) {
            // Assume AI returns newline-separated items
            $takeaways = explode("\n", $formatted_content);
            $formatted_content = '<ul>';
            foreach ($takeaways as $takeaway) {
                $takeaway = trim($takeaway);
                if (!empty($takeaway) && !preg_match('/^[-•*]/', $takeaway)) {
                    $takeaway = '• ' . $takeaway;
                }
                if (!empty($takeaway)) {
                    $formatted_content .= '<li>' . esc_html(ltrim($takeaway, '-•* ')) . '</li>';
                }
            }
            $formatted_content .= '</ul>';
        }
    } else {
        $formatted_content = wp_kses_post($summary);
    }
    
    $html = '<div class="ahmaipsu-summary-box ' . esc_attr($theme_class) . '">';
    if ($show_title) {
        $html .= '<p class="ahmaipsu-summary-title">' . esc_html($theme_title) . '</p>';
    }
    $html .= '<div class="ahmaipsu-summary-content">' . $formatted_content . '</div>';
    if ($show_disclaimer) {
        $html .= '<div class="ahmaipsu-summary-disclaimer"><small>ℹ️ ' . esc_html($disclaimer) . '</small></div>';
    }
    $html .= '</div>';
    return $html;
}

// Add CSS for summary display
add_action('wp_enqueue_scripts', 'ahmaipsu_frontend_styles');

function ahmaipsu_frontend_styles() {
    // Only enqueue on single posts/pages where we might show summaries
    if (!is_singular()) {
        return;
    }
    
    global $post;
    if (!$post) {
        return;
    }
    
    // Check if current post type is supported
    $options = get_option('ahmaipsu_settings', array());
    $supported_post_types = isset($options['ahmaipsu_post_types']) ? $options['ahmaipsu_post_types'] : ['post'];
    
    if (!in_array($post->post_type, $supported_post_types)) {
        return;
    }
    
    // Enqueue the external CSS file
    wp_enqueue_style(
        'ahmaipsu-frontend',
        AHMAIPSU_PLUGIN_URL . 'dist/css/frontend.min.css',
        array(),
        AHMAIPSU_VERSION
    );
}

// Canonical shortcode plus backward-compat alias. Do not register [ai_post_summary].
add_shortcode('ahm_ai_post_summary', 'ahmaipsu_shortcode');
add_shortcode('ahmaipsu', 'ahmaipsu_shortcode');

function ahmaipsu_shortcode($atts) {
    global $post;
    $summary = get_post_meta($post->ID, '_ahmaipsu_content', true);
    $content_type = get_post_meta($post->ID, '_ahmaipsu_content_type', true) ?: 'summary';
    
    if (empty($summary)) {
        return '';
    }
    
    // Get disclaimer text and theme from settings
    $options = get_option('ahmaipsu_settings');
    $disclaimer = $options['ahmaipsu_disclaimer'] ?? 'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.';
    $theme = $options['ahmaipsu_theme'] ?? 'classic';
    
    return ahmaipsu_render_summary($summary, $disclaimer, $theme, $content_type);
}
