<?php
/**
 * Frontend display for AI Post Summary plugin
 *
 * @package AIPostSummary
 * @since   1.0.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

add_filter('the_content', 'ahmaipsu_display_summary');

function ahmaipsu_display_summary($content) {
    // Only show on single posts and main query
    if (!is_single() || !is_main_query() || is_admin()) {
        return $content;
    }
    
    global $post;
    
    // Verify we have a valid post object
    if (!$post || !isset($post->ID)) {
        return $content;
    }
    
    $options = get_option('ahmaipsu_settings', array());
    $global_enabled = isset($options['ahmaipsu_global_enable']) ? $options['ahmaipsu_global_enable'] : false;
    $post_enabled = get_post_meta($post->ID, '_ahmaipsu_enabled', true);
    $summary = get_post_meta($post->ID, '_ahmaipsu_content', true);
    
    if (!$global_enabled || !$post_enabled || empty($summary)) {
        return $content;
    }
    
    // Get disclaimer text and theme from settings
    $disclaimer = isset($options['ahmaipsu_disclaimer']) ? 
        $options['ahmaipsu_disclaimer'] : 
        'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.';
    
    $theme = isset($options['ahmaipsu_theme']) ? $options['ahmaipsu_theme'] : 'classic';
    
    $summary_html = ahmaipsu_render_summary($summary, $disclaimer, $theme);
    
    return $summary_html . $content;
}

function ahmaipsu_render_summary($summary, $disclaimer, $theme = 'classic') {
    $theme_classes = array(
        'classic' => 'ahmaipsu-theme-classic',
        'minimal' => 'ahmaipsu-theme-minimal',
        'modern' => 'ahmaipsu-theme-modern',
        'elegant' => 'ahmaipsu-theme-elegant',
        'card' => 'ahmaipsu-theme-card'
    );
    
    $theme_titles = array(
        'classic' => '📝 Summary',
        'minimal' => 'Summary',
        'modern' => '🤖 AI Summary',
        'elegant' => 'Summary',
        'card' => '📄 Article Summary'
    );
    
    $theme_class = isset($theme_classes[$theme]) ? $theme_classes[$theme] : $theme_classes['classic'];
    $theme_title = isset($theme_titles[$theme]) ? $theme_titles[$theme] : $theme_titles['classic'];
    
    return '<div class="ahmaipsu-summary-box ' . esc_attr($theme_class) . '">
        <h4 class="ahmaipsu-summary-title">' . esc_html($theme_title) . '</h4>
        <div class="ahmaipsu-summary-content">' . wp_kses_post($summary) . '</div>
        <div class="ahmaipsu-summary-disclaimer">
            <small>ℹ️ ' . esc_html($disclaimer) . '</small>
        </div>
    </div>';
}

// Add CSS for summary display
add_action('wp_enqueue_scripts', 'ahmaipsu_frontend_styles');

function ahmaipsu_frontend_styles() {
    // Only enqueue on single posts where we might show summaries
    if (!is_single()) {
        return;
    }
    
    // Enqueue the external CSS file
    wp_enqueue_style(
        'ahmaipsu-frontend',
        AHMAIPSU_PLUGIN_URL . 'dist/css/frontend.min.css',
        array(),
        AHMAIPSU_VERSION
    );
}

// Shortcode for manual placement
add_shortcode('ahmaipsu', 'ahmaipsu_shortcode');

function ahmaipsu_shortcode($atts) {
    global $post;
    $summary = get_post_meta($post->ID, '_ahmaipsu_content', true);
    
    if (empty($summary)) {
        return '';
    }
    
    // Get disclaimer text and theme from settings
    $options = get_option('ahmaipsu_settings');
    $disclaimer = $options['ahmaipsu_disclaimer'] ?? 'This summary was generated by AI and may contain inaccuracies or omissions. Please refer to the full article for complete information.';
    $theme = $options['ahmaipsu_theme'] ?? 'classic';
    
    return ahmaipsu_render_summary($summary, $disclaimer, $theme);
}
